# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Madrasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_markaz', models.BooleanField(default=False)),
            ],
        ),
    ]
