# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.PositiveIntegerField(blank=True)),
                ('reg_year', models.CharField(choices=[('2016', '2016'), ('2017', '2017'), ('2018', '2018')], default='2017', max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('madrasa', models.CharField(max_length=100)),
                ('marhala', models.CharField(choices=[('takmil', 'Takmil'), ('fazilat', 'Fazilat'), ('hifz', 'Hifzul Quran')], max_length=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
