# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
