# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_deleted',
            new_name='is_active',
        ),
    ]
