# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20171118_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, help_text='permanent address of student', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='markaz',
            field=models.CharField(blank=True, help_text="If the student's madrasa is the markaz then leave it blank' otherwise enter the markaz name", max_length=127),
        ),
    ]
